function [status, msgError] = RawFileMetaData(fileName, measData)

    arguments
        fileName 
        measData
    end

    status = true;
    msgError = '';

    try
        jsonFileContent = struct( ...
            'Filename',              measData.Filename,            ...
            'Sensor',                measData.Sensor,              ...
            'Model',                 measData.MetaData.Model,      ...
            'Serial',                measData.MetaData.Serial,     ...
            'MeasCount',             measData.Measures,            ...
            'MeasStartTime',         measData.Data.Timestamp(1),   ...
            'MeasEndTime',           measData.Data.Timestamp(end), ...
            'FieldValueMin',         measData.FieldValueLimits(1), ...
            'FieldValueMax',         measData.FieldValueLimits(2), ...
            'LatitudeCentralPoint',  measData.Latitude,            ...
            'LongitudeCentralPoint', measData.Longitude,           ...
            'LatitudeBoxMin',        measData.LatitudeLimits(1),   ...
            'LatitudeBoxMax',        measData.LatitudeLimits(2),   ...
            'LongitudeBoxMin',       measData.LongitudeLimits(1),  ...
            'LongitudeBoxMax',       measData.LongitudeLimits(2),  ...
            'CoveredDistance',       measData.CoveredDistance ...
        );

        writematrix(jsonencode(jsonFileContent, "PrettyPrint", true), fileName, 'FileType', 'text', 'QuoteStrings', 'none', 'WriteMode', 'overwrite', 'Encoding', 'UTF-8')

    catch ME
        status = false;
        msgError = ME.message;
    end
end