classdef (Abstract) Table

    methods (Static)
        %-----------------------------------------------------------------%
        function Table = FileByLocation(dataOverview)
            Table = table('Size',          [0, 8],                                                                 ...
                          'VariableTypes', {'double', 'cell', 'cell', 'cell', 'cell', 'double', 'double', 'cell'}, ...
                          'VariableNames', {'#', 'Localidade de agrupamento', 'Localidades sob análise', 'Arquivo', 'Período de observação', 'Qtd. medidas', 'Qtd. medidas superior limar', 'Limites'});

            groupLocationList = {dataOverview.ID};

            for ii = 1:numel(groupLocationList)
                groupLocation = groupLocationList{ii};
                groupIndex    = find(strcmp(groupLocationList, groupLocation), 1);

                Table(end+1,:) = {...
                    ii, ...
                    groupLocation, ...
                    strjoin(dataOverview(groupIndex).InfoSet.locations,           '<br>'), ...
                    strjoin({dataOverview(groupIndex).InfoSet.measData.FileName}, '<br>'), ...
                    dataOverview(groupIndex).InfoSet.period, ...
                    dataOverview(groupIndex).InfoSet.numMeasurements, ...
                    sum(dataOverview(groupIndex).InfoSet.numAboveTHR), ...
                    dataOverview(groupIndex).InfoSet.limits ...
                };
            end
        end

        %-----------------------------------------------------------------%
        function Table = SummaryByLocation(analyzedData)
            measData = analyzedData.InfoSet.measData;
            measIdx  = analyzedData.Index;
            Table    = table('Size',          [0, 9],                                                                       ...
                             'VariableTypes', {'cell', 'cell', 'cell', 'cell', 'cell', 'cell', 'double', 'double', 'cell'}, ...
                             'VariableNames', {'#', 'Arquivo', 'Sensor', 'Metadados', 'Região', 'Período de observação', 'Qtd. medidas', 'Qtd. medidas superior limar', 'Limites'});
        
            for ii = 1:numel(measData)
                durationTime = measData(ii).Data.Timestamp(end) - measData(ii).Data.Timestamp(1);

                Table(end+1,:) = { ...
                    sprintf('%d.%d', measIdx, ii), ...
                    measData(ii).FileName, ...
                    measData(ii).Sensor, ...
                    jsonencode(measData(ii).MetaData), ...
                    jsonencode(struct('latLimits', measData(ii).LatitudeLimits, 'lngLimits', measData(ii).LongitudeLimits)), ...
                    sprintf('%s<br>⌛%s', measData(ii).ObservationTime, durationTime), ...
                    measData(ii).Measures, ...
                    analyzedData.InfoSet.numAboveTHR(ii), ...
                    sprintf('[%.1f - %.1f] V/m', measData(ii).FieldValueLimits(:)) ...
                };
            end
        end

        %-----------------------------------------------------------------%
        function varargout = PointsByLocation(analyzedData, measuredFlag, outputType)
            arguments
                analyzedData
                measuredFlag char {mustBeMember(measuredFlag, {'all', 'on', 'off'})} = 'all'
                outputType   char {mustBeMember(outputType, {'table', 'tableHeight'})} = 'table'
            end

            Table = analyzedData.InfoSet.pointsTable;
            
            switch measuredFlag
                case 'on'
                    Table = Table(Table.numberOfMeasures > 0, :);
                case 'off'
                    Table = Table(Table.numberOfMeasures == 0, :);
            end

            switch outputType
                case 'table'
                    varargout = {Table};
                case 'tableHeight'
                    varargout = {height(Table)};
            end
        end

        %-----------------------------------------------------------------%
        function varargout = StationsByLocation(analyzedData, measuredFlag, outputType)
            arguments
                analyzedData
                measuredFlag char {mustBeMember(measuredFlag, {'all', 'on', 'off'})} = 'all'
                outputType   char {mustBeMember(outputType, {'table', 'tableHeight'})} = 'table'
            end

            stationTable = analyzedData.InfoSet.stationTable;

            % Insere coordenadas geográficas da estação no campo "Observações", 
            % caso editadas, e troca valores inválidos ("-1", por exemplo) por 
            % valores nulos.
            Table = model.ProjectBase.normalizeStationTableAnnotations(stationTable, '-');

            switch measuredFlag
                case 'on'
                    Table = Table(Table.numberOfMeasures > 0, :);
                case 'off'
                    Table = Table(Table.numberOfMeasures == 0, :);
            end

            switch outputType
                case 'table'
                    varargout = {Table};
                case 'tableHeight'
                    varargout = {height(Table)};
            end
        end

        %-----------------------------------------------------------------%
        % TABELAS PARA SHAREPOINT (SCARAB)
        %-----------------------------------------------------------------%
        function jsonFileContent = scarabJsonFile(projectData, context, correlationKey, executionMode, issueDetails, generalSettings, EMFieldObj, referenceTable)
            entityGroupName = projectData.modules.(context).ui.entity.name;
            entityGroupId = projectData.modules.(context).ui.entity.id;

            jsonFileContent = struct( ...
                'schemaVersion', 1, ...
                'clientName', class.Constants.appName, ...
                'clientVersion', class.Constants.appVersion, ...
                'clientExecutionMode', executionMode, ...
                'auditorName', issueDetails.usuario.nome, ...
                'auditorEmail', issueDetails.usuario.email, ...
                'auditorDepartment', issueDetails.usuario.unidade, ...
                'auditorJobTitle', issueDetails.usuario.funcao, ...
                'project', struct( ...
                    'correlationKey', correlationKey, ...
                    'system', projectData.modules.(context).ui.system, ...
                    'issue', projectData.modules.(context).ui.issue, ...
                    'context', context, ...
                    'entityGroupName', entityGroupName, ...
                    'entityGroupId', entityGroupId, ...
                    'unit', projectData.modules.(context).ui.unit ...
                ), ...
                'rawFiles', [] ...
            );

            % RAWFILES
            rawFiles = table( ...
                'Size', [numel(EMFieldObj), 17], ...
                'VariableNames', {'correlationKey', 'fileName', 'sensorManufacturer', 'sensorModel', 'sensorSerialNumber', 'measurementStartTime', 'measurementEndTime', 'measurementCount', 'electricFieldMin', 'electricFieldMax', 'centralPointLat', 'centralPointLng', 'boundingBoxLatMin', 'boundingBoxLatMax', 'boundingBoxLngMin', 'boundingBoxLngMax', 'coveredDistanceKm'}, ...
                'VariableTypes', {'cell', 'cell', 'cell', 'cell', 'cell', 'cell', 'cell', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double', 'double'} ...
            );

            for ii = 1:numel(EMFieldObj)
                rawFiles(ii, :) = { ...
                    correlationKey,                     ...
                    EMFieldObj(ii).FileName,            ...
                    EMFieldObj(ii).Sensor,              ...
                    EMFieldObj(ii).MetaData.Model,      ...
                    EMFieldObj(ii).MetaData.Serial,     ...
                    datestr(EMFieldObj(ii).Data.Timestamp(1),   'yyyymmdd HH:MM:SS'), ...
                    datestr(EMFieldObj(ii).Data.Timestamp(end), 'yyyymmdd HH:MM:SS'), ...
                    EMFieldObj(ii).Measures,            ...
                    EMFieldObj(ii).FieldValueLimits(1), ...
                    EMFieldObj(ii).FieldValueLimits(2), ...
                    EMFieldObj(ii).Latitude,            ...
                    EMFieldObj(ii).Longitude,           ...
                    EMFieldObj(ii).LatitudeLimits(1),   ...
                    EMFieldObj(ii).LatitudeLimits(2),   ...
                    EMFieldObj(ii).LongitudeLimits(1),  ...
                    EMFieldObj(ii).LongitudeLimits(2),  ...
                    EMFieldObj(ii).CoveredDistanceKm ...
                };
            end

            jsonFileContent.rawFiles = rawFiles;

            % STATIONTABLE & POINTSTABLE
            referenceTable = model.ProjectBase.prepareReferenceTableToExport(context, referenceTable, generalSettings);
            referenceTable.('correlationKey')(:) = {correlationKey};
            referenceTable = movevars(referenceTable, 'correlationKey', 'Before', 1);

            switch context
                case 'MONITORINGPLAN'
                    jsonFileContent.stationTable = referenceTable;

                case 'EXTERNALREQUEST'
                    jsonFileContent.pointsTable  = referenceTable;
            end

            jsonFileContent = jsonencode(jsonFileContent, 'PrettyPrint', true);
        end

        %-----------------------------------------------------------------%
        function teamsFileContent = scarabTeamsFileContent(issueDetails, sharepointFileList)
            teamsFileContent = struct( ...
                'schemaVersion', 1, ...
                'clientName', class.Constants.appName, ...
                'auditorName', issueDetails.usuario.nome, ...
                'auditorEmail', issueDetails.usuario.email, ...
                'fileNameList', {sharepointFileList} ...
            );

            teamsFileContent = jsonencode(teamsFileContent, 'PrettyPrint', true);
        end
    end
end