function htmlContent = HTMLList(rawSCHTable, idx, rootFolder)

    htmlBase = HTMLBase('Table');

    [uniqueHomValues, ia, ic] = unique(rawSCHTable.("Homologação")(idx), 'stable');


    htmlList = repmat({''}, numel(idx), 1);

    for ii = 1:numel(uniqueHomValues)
        firstIndex   = idx(ia(ii));
        allIndex     = idx(ic==ii);

        ID           = char(uniqueHomValues(ii));
        Status       = char(rawSCHTable.("Situação")(firstIndex));
        StatusColor  = '';
        if ismember(Status, {'Homologação Anulada', 'Homologação Cancelada', 'Homologação Suspensa', 'Requerimento - Cancelado'})
            StatusColor = ' style="color:red;"';
        end

        Manufacturer = char(rawSCHTable.("Fabricante")(firstIndex));
        Model        = char(rawSCHTable.("Modelo")(firstIndex));
        TradeName    = char(rawSCHTable.("Nome Comercial")(firstIndex));
        ProductType  = strjoin(unique(cellstr(rawSCHTable.("Tipo")(allIndex))), '<br>');

        imgFullFile  = fullfile(rootFolder, 'Icons', sprintf('flag%s.png', rawSCHTable.("CodISO")(firstIndex)));
        if isfile(imgFullFile)
            [~, imgString] = ccTools.fcn.img2base64(imgFullFile);
        else
            imgString      = 'iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJiSURBVGhD7Zk/b9pAGMaxDcYR2ICgCKpKRhSFgSZDJTIlEksVqsLeIWOHfoEMyZQPkClD1yyZEnWiH6RTMiQS8pBKAQkR6grLBbvPwcVJ1ESJYjsG5X7SK7/3R/A+3PnuvSPEYDDmG4E+faFer3Oqqobb7bZFq+aDfD7/Spblr6Io/pAk6Wc0Gt1PpVLr5XKZp11mm3g8vsPz/CVcm5oVDoe1dDr9nrTPNAhSikQiF3CvgncMI7GHp6d4PqS2bZPPlKal26AtSl3P8FxAoVAwMF0O4f6d1kzhOE6PxWLfaXG2URRlES/wId4DA0Uy/7uYPlvFYlGc9pgDqtWqmEwmlxH4Wi6XUxuNBkebGIwXBea/kkgk3lYqlQVa5Sm+5EK1Wo0bjUYprEIfBoPBrmman+Gf6Lqu0S6e4XZlUGFfsMZHsGzGsQMr8NOGYbwej8dvLMvKkE6CIAywQ290Op0WKc8Sq7Ah7L+04aZBwGU2m23A9xxXOzGyTh2b1jECPMUvf4qqM2KYLr8nHa65EjMf4KX9CFFOQge/jxH4NGn0GF/yc4zGL6QPf2jRV/wSQD3/8UXAc8IEBA0TEDRMQNAwAUHDBAQNExA0TMBd2LZN8umbOTXxfblAcJW4ZzIZBYf3dwjYCQ5nAcE0zepwONzGoT5J6yxJkvZhByiSU9rke1Fvy7J8pmnaOSk/BVcCcOpaweMIApw7HwTFI3AZdusil4ggR0u4zt9NVMBOr9f7RquenUfdStxnRBTOz5vwn4yrEWg2m3K3213q9/t3/qHxEERAqVQ6brVaHVrFYDBeFqHQPwNXrRGhF/9eAAAAAElFTkSuQmCC';
        end

        htmlList{ii} = sprintf([htmlBase '<br><br>'], imgString, ID, StatusColor, upper(Status), Manufacturer, Model, TradeName, ProductType);
    end

    htmlContent = [sprintf(HTMLBase('Header')), ...
                   strjoin(htmlList),           ...
                   sprintf(HTMLBase('Trailer'))];
end



%-------------------------------------------------------------------------%
function htmlContent = HTMLBase(Type)
    htmlBase = ['<!DOCTYPE html>\n' ...
                '<html>\n\t' ...
                    '<head>\n\t\t' ...
                        '<style>\n\t\t\t' ...
                            'body {\n\t\t\t\t' ...
                                'font-family: ''Helvetica'', Arial, sans-serif;\n\t\t\t' ...
                            '}\n\t\t\t' ...
                            '.ID {\n\t\t\t\t' ...
                                'font-size: 16px;\n\t\t\t\t' ...
                                'font-weight: bold;\n\t\t\t' ...
                            '}\n\t\t\t' ...
                            '.Status {\n\t\t\t\t' ...
                                'font-size: 10px;\n\t\t\t\t' ...
                            '}\n\t\t\t' ...
                            '.Description {\n\t\t\t\t' ...
                                'font-size: 11px;\n\t\t\t\t' ...
                                'color: gray;\n\t\t\t' ...
                            '}\n\t\t\t' ...
                            '.Specifications {\n\t\t\t\t' ...
                                'font-size: 12px;\n\t\t\t' ...
                            '}\n\t\t\t' ...
                            'table {\n\t\t\t\t' ...
                                'width: auto;\n\t\t\t' ...
                            '}\n\t\t\t' ...
                            'th, td {\n\t\t\t\t' ...
                                'border: none;\n\t\t\t\t' ...
                                'text-align: left;\n\t\t\t' ...
                            '}\n\t\t\t' ...
                            'tr {\n\t\t\t\t' ...
                                'line-height: 12px;\n\t\t\t' ...
                            '}\n\t\t' ...
                        '</style>\n\t\t' ...
                    '</head>\n\t' ...
                    '<body>\n\t\t' ...
                        '<table>\n\t\t\t' ...
                            '<tr>\n\t\t\t\t' ...
                                '<td style="width: 40px;">\n\t\t\t\t\t' ...
                                    '<img src="data:image/png;base64,%s"/>\n\t\t\t\t' ...
                                '</td>\n\t\t\t\t' ...
                                '<td>\n\t\t\t\t\t' ...
                                    '<a class="ProductLink" href="#">\n\t\t\t\t\t\t' ...
                                        '<span class="ID">%s</span>\n\t\t\t\t\t' ...
                                    '</a>\n\t\t\t\t\t' ...
                                    '<span class="Status"%s>&nbsp;&nbsp;%s</span><br>\n\t\t\t\t\t' ...
                                    '<span class="Description">%s<br>%s (%s)</span><br>\n\t\t\t\t' ...
                                '</td>\n\t\t\t' ...
                            '</tr>\n\t\t\t' ...
                            '<tr>\n\t\t\t\t' ...
                                '<td colspan="2" class="Specifications">\n\t\t\t\t\t' ...
                                    '%s\n\t\t\t\t' ...
                                '</td>\n\t\t\t' ...
                            '</tr>\n\t\t' ...
                        '</table>\n\t\t' ...
                        '<script>\n\t\t\t' ...
                            'function setup(htmlComponent) {\n\t\t\t\t' ...
                                'document.body.addEventListener("click", function(event) {\n\t\t\t\t\t' ...
                                    'if (event.target.classList.contains("ID")) {\n\t\t\t\t\t\t' ...
                                        'htmlComponent.sendEventToMATLAB("clickedLink", event.target.textContent);\n\t\t\t\t\t\t' ...
                                        'event.preventDefault();\n\t\t\t\t\t' ...
                                    '}\n\t\t\t\t' ...
                                '});\n\t\t\t' ...
                            '}\n\t\t' ...
                        '</script>\n\t' ...
                    '</body>\n' ...
                '</html>'];

    switch Type
        case 'all';     htmlContent = htmlBase;
        case 'Header';  htmlContent = char(extractBetween(htmlBase, '<!DOCTYPE html>', '<body>\n\t\t',   'Boundaries', 'inclusive'));
        case 'Table';   htmlContent = char(extractBetween(htmlBase, '<table>',         '</table>\n\t\t', 'Boundaries', 'inclusive'));
        case 'Trailer'; htmlContent = char(extractBetween(htmlBase, '<script>',        '</html>',        'Boundaries', 'inclusive'));
    end
end