function pointsTable = ExternalRequest(appGeneral)
    
    pointsTable = table('Size',          [0, 18],                                                                  ...
                        'VariableTypes', {'cell', 'cell', 'int32', 'double', 'double', 'cell',                     ...
                                          'double', 'double', 'double', 'double', 'double',                        ...
                                          'double', 'double', 'double', 'cell', 'categorical', 'cell', 'logical'}, ...
                        'VariableNames', {'ID', 'Type', 'Station', 'Latitude', 'Longitude', 'Description',         ...
                                          'numberOfMeasures', 'numberOfRiskMeasures', 'minDistanceForMeasure',     ...
                                          'minFieldValue', 'meanFieldValue', 'maxFieldValue', 'maxFieldLatitude',  ...
                                          'maxFieldLongitude', 'Fonte de dados', 'Justificativa', 'Observações', 'AnalysisFlag'});

    pointsTable.Justificativa = categorical(pointsTable.Justificativa, appGeneral.ExternalRequest.NoMeasureReasons);
    
end