function pointsTable = ExternalRequest(appGeneral)
    
    pointsTable = table('Size',          [0, 16],                                                                 ...
                        'VariableTypes', {'cell', 'cell', 'int32', 'double', 'double', 'cell',                    ...
                                          'double', 'double', 'double', 'double', 'double',                       ...
                                          'double', 'double', 'double', 'categorical','logical'},                 ...
                        'VariableNames', {'ID', 'Type', 'Station', 'Latitude', 'Longitude', 'Description',        ...
                                          'numberOfMeasures', 'numberOfRiskMeasures', 'minDistanceForMeasure',    ...
                                          'minFieldValue', 'meanFieldValue', 'maxFieldValue', 'maxFieldLatitude', ...
                                          'maxFieldLongitude', 'Justificativa', 'AnalysisFlag'});

    pointsTable.Justificativa = categorical(pointsTable.Justificativa, appGeneral.ExternalRequest.NoMeasureReasons);
    
end