function pointsTable = ExternalRequest()
    
    pointsTable = table('Size',          [0, 15],                                                                 ...
                        'VariableTypes', {'cell', 'cell', 'int32', 'double', 'double', 'cell',                    ...
                                          'double', 'double', 'double', 'double', 'double',                       ...
                                          'double', 'double', 'double', 'logical'},                               ...
                        'VariableNames', {'ID', 'Type', 'Station', 'Latitude', 'Longitude', 'Description',        ...
                                          'numberOfMeasures', 'numberOfRiskMeasures', 'minDistanceForMeasure',    ...
                                          'minFieldValue', 'meanFieldValue', 'maxFieldValue', 'maxFieldLatitude', ...
                                          'maxFieldLongitude', 'AnalysisFlag'});
    
end